### ISSUE TITLE
random prediction of  serotype 45 and 19C

### ISSUE THREAD

**Issue by eppinglen** [phe-bioinformatics/PneumoCaT#1] opened 2017-05-11 09:42 UTC
I tried to reprdouce the results from https://peerj.com/articles/2477/ on the validation dataset with PneumoCat v.1.1. However, the result for several samples was serotype 45 and 19C in the second value, which is not correct. This happens in 117 cases. Can you reproduce the bug with sample: ERR1439524
ERR1439514
ERR1439197
?
I used Bowtie2 2.2.9 and Samtools 0.1.19 as recommended on your git. If you like to I can sent you a complete list of all samples that produced an other result as in https://peerj.com/articles/2477/ .

**Comment by gkapatai** [comment] 2017-05-11 12:16
First of all, thanks for using PneumoCaT. I am aware of some inconsistencies between the ERR number and the PHE numbers mentioned in the paper. I tried resolving this once by updating the tables but there is still some inconsistency.  I would really appreciate if you could send me the list of all samples that produced different than expected result so that i can compare with my list. As for the bug, I will look into it today and get back to you ASAP.

**Comment by eppinglen** [comment] 2017-05-11 12:44
I think the  PHE and ERR numbers are consistent in the updated tables.
Here is a list of all samples with different predictions and the result I got from PneumoCat. For me it seems like a systematical bug. 
[PneumoCat_Paper_comp_PneumCatV1.1.xlsx](https://github.com/phe-bioinformatics/PneumoCaT/files/992998/PneumoCat_Paper_comp_PneumCatV1.1.xlsx)

**Comment by gkapatai** [comment] 2017-05-11 14:12
OK, I have looked into the samples you indicated and I can now confirm that
the problem is not within the pipeline but the file itself. Unfortunately,
we encountered that problem before. For some of the isolates, the files
under the FASTQ files (FTP) heading are not the same as the ones submitted
(found under Submitted files (FTP)). For each of the three isolates you
indicated I downloaded both the FASTQ files (FTP) and the Submitted files
(FTP) and run PneumoCaT on both of them. All three file pairs downloaded
from the Submitted  files (FTP) column where run and produced the expected
result. However the files downloaded from the  FASTQ files (FTP) column
where taking too long to run. Also if you compare the file size for the
FASTQ files (FTP) and Submitted Files (FTP) for the same sample you will
notice that they differ. We are not sure how this error happened during
submission to ENA but it has been an issue before and we are trying to
resolve in collaboration with ENA.

Regarding the table you sent me, I would repeat the ones that are
discordant using the files under the   Submitted files (FTP) column.
However, I noticed you had some isolates where the mapped result was in the
same serogroup as the original result. Should I assume you did not have any
SNP_based_serotyping folder in any of them?  If this folder is present the
final result.xml is the one within that folder which takes into account the
serotype specific mutation profiles...

Please try this solution and let me know how it goes... In the meantime I
can use your list to liaise with ENA.

*Georgia Kapatai, PhD*
Bioinformatician, RVBPRU
Microbiology Services
Public Health England
61 Colindale Avenue
London NW9 5EQ

Tel: +44 (0) 208 327 6793
Mob: +44 (0) 7900694713

**Comment by eppinglen** [comment] 2017-05-12 11:52
I tried this and it is a lot better now. Thank you for the help. I still got some different results for samples:
ERR1439144
ERR1439570
ERR1439571
ERR1439572
ERR1439588
ERR1439591
ERR1439997.
PneumoCat predicts 12F instead of 12B, even in the SNP_based_serotyping folder.

**Comment by gkapatai** [comment] 2017-05-12 13:30
This is expected and relates to a change in the latest version of the database. It appears our phenotypic method of slide agglutination was mistyping our 12Bs as 12Fs and this reflected in the selection of mutations. Earlier in the year a colleague from Sanger identified an interesting clone of 12Fs that corresponded to our 12Bs and since then we updated the database to now identify all 12Fs including the misbehaving clone. If these are the only different results then I would say that PneumoCaT is behaving as it should and we can now close this issue. :)

**Closed** 2017-05-12 13:32 UTC
